// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.1.0.0
//      SpecFlow Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace PackageUseScrutiniser.Core.Tests.PackageFinderTests
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SearchingForPackageConfigsContainingAPackageIdFeature : Xunit.IClassFixture<SearchingForPackageConfigsContainingAPackageIdFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "GettingPackages.feature"
#line hidden
        
        public SearchingForPackageConfigsContainingAPackageIdFeature()
        {
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Searching for package configs containing a package id", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void SetFixture(SearchingForPackageConfigsContainingAPackageIdFeature.FixtureData fixtureData)
        {
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Packages exists with requested package id")]
        [Xunit.TraitAttribute("FeatureTitle", "Searching for package configs containing a package id")]
        [Xunit.TraitAttribute("Description", "Packages exists with requested package id")]
        public virtual void PackagesExistsWithRequestedPackageId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Packages exists with requested package id", ((string[])(null)));
#line 3
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "File name",
                        "content"});
            table1.AddRow(new string[] {
                        "package1.config",
                        "<?xml version=\"1.0\" encoding=\"utf-8\"?><packages><package id=\"package id\"/></packa" +
                            "ges>"});
            table1.AddRow(new string[] {
                        "package2.config",
                        "<?xml version=\"1.0\" encoding=\"utf-8\"?><packages><package id=\"other package id\" />" +
                            "</packages>"});
#line 4
  testRunner.Given("There are packages.config files with content", ((string)(null)), table1, "Given ");
#line 8
  testRunner.When("getting packages with \"package id\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "package file name"});
            table2.AddRow(new string[] {
                        "package1.config"});
#line 9
  testRunner.Then("return packages containing package id", ((string)(null)), table2, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="Packages do not exist with requested package id")]
        [Xunit.TraitAttribute("FeatureTitle", "Searching for package configs containing a package id")]
        [Xunit.TraitAttribute("Description", "Packages do not exist with requested package id")]
        public virtual void PackagesDoNotExistWithRequestedPackageId()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Packages do not exist with requested package id", ((string[])(null)));
#line 13
 this.ScenarioSetup(scenarioInfo);
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "File name",
                        "content"});
            table3.AddRow(new string[] {
                        "package1.config",
                        "<?xml version=\"1.0\" encoding=\"utf-8\"?><packages><package id=\"other package id\"/><" +
                            "/packages>"});
            table3.AddRow(new string[] {
                        "package2.config",
                        "<?xml version=\"1.0\" encoding=\"utf-8\"?><packages><package id=\"other other package " +
                            "id\" /></packages>"});
#line 14
  testRunner.Given("There are packages.config files with content", ((string)(null)), table3, "Given ");
#line 18
  testRunner.When("getting packages with \"package id\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "package file name"});
#line 19
  testRunner.Then("return packages containing package id", ((string)(null)), table4, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.1.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                SearchingForPackageConfigsContainingAPackageIdFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                SearchingForPackageConfigsContainingAPackageIdFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
